name: Laundry_Queueing_Application

on:
  push:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Use API key
      run: echo "Using API key: $API_KEY"